# Import Numpy as NP

In [1]:
import numpy as np

# Create an array of 10 zero's

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create an Array of 10 One's

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Create an array of 10 fives

In [7]:
np.array([5,5,5,5,5,5,5,5,5,5])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# Create an Array of numbers 10 to 50

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# Create an Array of even integers from 10-50

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# Create a 3x3 Matrix with values ranging from 0-8

In [12]:
myMatrix = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [13]:
myMatrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Use Numpy to generate a random number from 0-1

In [14]:
np.random.randn(1)

array([0.22940028])

# Create a matrix using the following statements:
## a. mat = np.arange(1,26).reshape(5)
### b. mat

In [18]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# a. Get the sum of all the values in the mat matrix

In [20]:
mat.sum()

325

# b. Get the standard deviation of the values in the mat matrix

In [21]:
mat.std()

7.211102550927978

# c. Create a new matrix of 25 ones named mat1

In [23]:
mat1 = np.ones(25)
mat1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

# d. Add the values of mat to those of mat1

In [24]:
mat.sum() + mat1.sum()

350.0

# e. Multiply the values of mat to those of mat1

In [26]:
mat.sum() * mat1.sum()

8125.0